var columnsData = {
  "us": { "order": 00001, "selected": true, "locked": true, "draggable": true, "resizable": true, "header": "United States", "title": "United States in NORTH AMERICA code us", "name": "United States" },
  "uk": { "order": 00002, "selected": true, "locked": true, "draggable": true, "resizable": true, "header": "United Kingdom", "title": "United Kingdom in EUROPE code uk", "name": "United Kingdom" },
  "fr": { "order": 00003, "selected": true, "locked": true, "draggable": true, "resizable": true, "header": "France", "title": "France in EUROPE code fr", "name": "France" },
  "ru": { "order": 00004, "selected": true, "locked": true, "draggable": true, "resizable": true, "header": "Russian Federation", "title": "Russian Federation in ASIA code ru", "name": "Russian Federation" },
  "cn": { "order": 00005, "selected": true, "locked": true, "draggable": true, "resizable": true, "header": "China", "title": "China in ASIA code cn", "name": "China" },
  "mk": { "order": 00636, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Macedonia", "title": "Macedonia in EUROPE code mk", "name": "Macedonia" },
  "gq": { "order": 01203, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Equatorial Guinea", "title": "Equatorial Guinea in AFRICA code gq", "name": "Equatorial Guinea" },
  "lt": { "order": 01244, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Lithuania", "title": "Lithuania in EUROPE code lt", "name": "Lithuania" },
  "sc": { "order": 01611, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Seychelles", "title": "Seychelles in AFRICA code sc", "name": "Seychelles" },
  "iq": { "order": 02461, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Iraq", "title": "Iraq in ASIA code iq", "name": "Iraq" },
  "ss": { "order": 02592, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "South Sudan", "title": "South Sudan in AFRICA code ss", "name": "South Sudan" },
  "sd": { "order": 02762, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Sudan", "title": "Sudan in AFRICA code sd", "name": "Sudan" },
  "sv": { "order": 03004, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "El Salvador", "title": "El Salvador in NORTH AMERICA code sv", "name": "El Salvador" },
  "cr": { "order": 04246, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Costa Rica", "title": "Costa Rica in NORTH AMERICA code cr", "name": "Costa Rica" },
  "vn": { "order": 04389, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Vietnam", "title": "Vietnam in ASIA code vn", "name": "Vietnam" },
  "ph": { "order": 04625, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Philippines", "title": "Philippines in ASIA code ph", "name": "Philippines" },
  "mv": { "order": 04648, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Maldives", "title": "Maldives in ASIA code mv", "name": "Maldives" },
  "pe": { "order": 04757, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Peru", "title": "Peru in SOUTH AMERICA code pe", "name": "Peru" },
  "pa": { "order": 05195, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Panama", "title": "Panama in NORTH AMERICA code pa", "name": "Panama" },
  "li": { "order": 05558, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Liechtenstein", "title": "Liechtenstein in EUROPE code li", "name": "Liechtenstein" },
  "hn": { "order": 05678, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Honduras", "title": "Honduras in NORTH AMERICA code hn", "name": "Honduras" },
  "nr": { "order": 06016, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Nauru", "title": "Nauru in OCEANIA code nr", "name": "Nauru" },
  "bw": { "order": 06564, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Botswana", "title": "Botswana in AFRICA code bw", "name": "Botswana" },
  "de": { "order": 06578, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Germany", "title": "Germany in EUROPE code de", "name": "Germany" },
  "gd": { "order": 06645, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Grenada", "title": "Grenada in NORTH AMERICA code gd", "name": "Grenada" },
  "dj": { "order": 07217, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Djibouti", "title": "Djibouti in AFRICA code dj", "name": "Djibouti" },
  "bn": { "order": 07845, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Brunei", "title": "Brunei in ASIA code bn", "name": "Brunei" },
  "gh": { "order": 08383, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Ghana", "title": "Ghana in AFRICA code gh", "name": "Ghana" },
  "cl": { "order": 08726, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Chile", "title": "Chile in SOUTH AMERICA code cl", "name": "Chile" },
  "mc": { "order": 08909, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Monaco", "title": "Monaco in EUROPE code mc", "name": "Monaco" },
  "la": { "order": 10005, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Laos", "title": "Laos in ASIA code la", "name": "Laos" },
  "er": { "order": 10489, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Eritrea", "title": "Eritrea in AFRICA code er", "name": "Eritrea" },
  "am": { "order": 10862, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Armenia", "title": "Armenia in EUROPE code am", "name": "Armenia" },
  "cf": { "order": 10891, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Central African Republic", "title": "Central African Republic in AFRICA code cf", "name": "Central African Republic" },
  "ye": { "order": 12254, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Yemen", "title": "Yemen in ASIA code ye", "name": "Yemen" },
  "or": { "order": 12705, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "East Timor", "title": "East Timor in ASIA code or", "name": "East Timor" },
  "tg": { "order": 13538, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Togo", "title": "Togo in AFRICA code tg", "name": "Togo" },
  "bf": { "order": 13778, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Burkina", "title": "Burkina in AFRICA code bf", "name": "Burkina" },
  "be": { "order": 13886, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Belgium", "title": "Belgium in EUROPE code be", "name": "Belgium" },
  "to": { "order": 13937, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Tonga", "title": "Tonga in OCEANIA code to", "name": "Tonga" },
  "st": { "order": 15178, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Sao Tome and Principe", "title": "Sao Tome and Principe in AFRICA code st", "name": "Sao Tome and Principe" },
  "mw": { "order": 15334, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Malawi", "title": "Malawi in AFRICA code mw", "name": "Malawi" },
  "ar": { "order": 15538, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Argentina", "title": "Argentina in SOUTH AMERICA code ar", "name": "Argentina" },
  "se": { "order": 15665, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Sweden", "title": "Sweden in EUROPE code se", "name": "Sweden" },
  "mj": { "order": 15669, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Montenegro", "title": "Montenegro in EUROPE code mj", "name": "Montenegro" },
  "ee": { "order": 16079, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Estonia", "title": "Estonia in EUROPE code ee", "name": "Estonia" },
  "ve": { "order": 16691, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Venezuela", "title": "Venezuela in SOUTH AMERICA code ve", "name": "Venezuela" },
  "gw": { "order": 16939, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Guinea-Bissau", "title": "Guinea-Bissau in AFRICA code gw", "name": "Guinea-Bissau" },
  "za": { "order": 16992, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "South Africa", "title": "South Africa in AFRICA code za", "name": "South Africa" },
  "ae": { "order": 17389, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "United Arab Emirates", "title": "United Arab Emirates in ASIA code ae", "name": "United Arab Emirates" },
  "pg": { "order": 18164, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Papua New Guinea", "title": "Papua New Guinea in OCEANIA code pg", "name": "Papua New Guinea" },
  "mx": { "order": 19153, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Mexico", "title": "Mexico in NORTH AMERICA code mx", "name": "Mexico" },
  "ht": { "order": 19341, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Haiti", "title": "Haiti in NORTH AMERICA code ht", "name": "Haiti" },
  "ch": { "order": 19992, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Switzerland", "title": "Switzerland in EUROPE code ch", "name": "Switzerland" },
  "mg": { "order": 20335, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Madagascar", "title": "Madagascar in AFRICA code mg", "name": "Madagascar" },
  "fm": { "order": 20655, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Micronesia", "title": "Micronesia in OCEANIA code fm", "name": "Micronesia" },
  "nz": { "order": 21608, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "New Zealand", "title": "New Zealand in OCEANIA code nz", "name": "New Zealand" },
  "vc": { "order": 22617, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Saint Vincent and the Grenadines", "title": "Saint Vincent and the Grenadines in NORTH AMERICA code vc", "name": "Saint Vincent & the Grenadines" },
  "bh": { "order": 23791, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Bahrain", "title": "Bahrain in ASIA code bh", "name": "Bahrain" },
  "sl": { "order": 23802, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Sierra Leone", "title": "Sierra Leone in AFRICA code sl", "name": "Sierra Leone" },
  "uy": { "order": 24072, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Uruguay", "title": "Uruguay in SOUTH AMERICA code uy", "name": "Uruguay" },
  "bo": { "order": 24117, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Bolivia", "title": "Bolivia in SOUTH AMERICA code bo", "name": "Bolivia" },
  "lc": { "order": 24194, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Saint Lucia", "title": "Saint Lucia in NORTH AMERICA code lc", "name": "Saint Lucia" },
  "co": { "order": 24269, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Colombia", "title": "Colombia in SOUTH AMERICA code co", "name": "Colombia" },
  "mh": { "order": 24949, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Marshall Islands", "title": "Marshall Islands in OCEANIA code mh", "name": "Marshall Islands" },
  "ke": { "order": 25841, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Kenya", "title": "Kenya in AFRICA code ke", "name": "Kenya" },
  "is": { "order": 26030, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Iceland", "title": "Iceland in EUROPE code is", "name": "Iceland" },
  "lr": { "order": 27132, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Liberia", "title": "Liberia in AFRICA code lr", "name": "Liberia" },
  "ao": { "order": 27822, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Angola", "title": "Angola in AFRICA code ao", "name": "Angola" },
  "ma": { "order": 27905, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Morocco", "title": "Morocco in AFRICA code ma", "name": "Morocco" },
  "km": { "order": 28106, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Comoros", "title": "Comoros in AFRICA code km", "name": "Comoros" },
  "mj": { "order": 28847, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Serbia", "title": "Serbia in EUROPE code mj", "name": "Serbia" },
  "py": { "order": 28907, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Paraguay", "title": "Paraguay in SOUTH AMERICA code py", "name": "Paraguay" },
  "jo": { "order": 28953, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Jordan", "title": "Jordan in ASIA code jo", "name": "Jordan" },
  "il": { "order": 29646, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Israel", "title": "Israel in ASIA code il", "name": "Israel" },
  "kz": { "order": 29713, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Kazakhstan", "title": "Kazakhstan in ASIA code kz", "name": "Kazakhstan" },
  "rw": { "order": 29834, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Rwanda", "title": "Rwanda in AFRICA code rw", "name": "Rwanda" },
  "jp": { "order": 29918, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Japan", "title": "Japan in ASIA code jp", "name": "Japan" },
  "ua": { "order": 31033, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Ukraine", "title": "Ukraine in EUROPE code ua", "name": "Ukraine" },
  "kg": { "order": 31225, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Kyrgyzstan", "title": "Kyrgyzstan in ASIA code kg", "name": "Kyrgyzstan" },
  "sn": { "order": 31275, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Senegal", "title": "Senegal in AFRICA code sn", "name": "Senegal" },
  "ir": { "order": 32541, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Iran", "title": "Iran in ASIA code ir", "name": "Iran" },
  "mz": { "order": 33210, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Mozambique", "title": "Mozambique in AFRICA code mz", "name": "Mozambique" },
  "tz": { "order": 34214, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Tanzania", "title": "Tanzania in AFRICA code tz", "name": "Tanzania" },
  "pw": { "order": 34243, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Palau", "title": "Palau in OCEANIA code pw", "name": "Palau" },
  "lk": { "order": 34596, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Sri Lanka", "title": "Sri Lanka in ASIA code lk", "name": "Sri Lanka" },
  "no": { "order": 35043, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Norway", "title": "Norway in EUROPE code no", "name": "Norway" },
  "bj": { "order": 35793, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Benin", "title": "Benin in AFRICA code bj", "name": "Benin" },
  "gy": { "order": 36939, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Guyana", "title": "Guyana in SOUTH AMERICA code gy", "name": "Guyana" },
  "sg": { "order": 37107, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Singapore", "title": "Singapore in ASIA code sg", "name": "Singapore" },
  "ug": { "order": 37309, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Uganda", "title": "Uganda in AFRICA code ug", "name": "Uganda" },
  "pk": { "order": 38217, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Pakistan", "title": "Pakistan in ASIA code pk", "name": "Pakistan" },
  "uz": { "order": 39148, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Uzbekistan", "title": "Uzbekistan in ASIA code uz", "name": "Uzbekistan" },
  "by": { "order": 41207, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Belarus", "title": "Belarus in EUROPE code by", "name": "Belarus" },
  "ls": { "order": 41733, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Lesotho", "title": "Lesotho in AFRICA code ls", "name": "Lesotho" },
  "bb": { "order": 41946, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Barbados", "title": "Barbados in NORTH AMERICA code bb", "name": "Barbados" },
  "cu": { "order": 42391, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Cuba", "title": "Cuba in NORTH AMERICA code cu", "name": "Cuba" },
  "mu": { "order": 42741, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Mauritius", "title": "Mauritius in AFRICA code mu", "name": "Mauritius" },
  "om": { "order": 43236, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Oman", "title": "Oman in ASIA code om", "name": "Oman" },
  "ro": { "order": 43696, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Romania", "title": "Romania in EUROPE code ro", "name": "Romania" },
  "th": { "order": 44680, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Thailand", "title": "Thailand in ASIA code th", "name": "Thailand" },
  "cz": { "order": 45429, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Czech Republic", "title": "Czech Republic in EUROPE code cz", "name": "Czech Republic" },
  "al": { "order": 45716, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Albania", "title": "Albania in EUROPE code al", "name": "Albania" },
  "dz": { "order": 45929, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Algeria", "title": "Algeria in AFRICA code dz", "name": "Algeria" },
  "ws": { "order": 47527, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Samoa", "title": "Samoa in OCEANIA code ws", "name": "Samoa" },
  "bt": { "order": 47865, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Bhutan", "title": "Bhutan in ASIA code bt", "name": "Bhutan" },
  "sr": { "order": 48153, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Suriname", "title": "Suriname in SOUTH AMERICA code sr", "name": "Suriname" },
  "mr": { "order": 48669, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Mauritania", "title": "Mauritania in AFRICA code mr", "name": "Mauritania" },
  "tv": { "order": 48871, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Tuvalu", "title": "Tuvalu in OCEANIA code tv", "name": "Tuvalu" },
  "ga": { "order": 49954, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Gabon", "title": "Gabon in AFRICA code ga", "name": "Gabon" },
  "mm": { "order": 50594, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Burma/Myanmar", "title": "Burma/Myanmar in ASIA code mm", "name": "Burma/Myanmar" },
  "sk": { "order": 50789, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Slovakia", "title": "Slovakia in EUROPE code sk", "name": "Slovakia" },
  "pt": { "order": 51466, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Portugal", "title": "Portugal in EUROPE code pt", "name": "Portugal" },
  "gn": { "order": 51627, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Guinea", "title": "Guinea in AFRICA code gn", "name": "Guinea" },
  "md": { "order": 52528, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Moldova", "title": "Moldova in EUROPE code md", "name": "Moldova" },
  "ki": { "order": 52696, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Kiribati", "title": "Kiribati in OCEANIA code ki", "name": "Kiribati" },
  "kr": { "order": 56302, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Korea, South", "title": "Korea, South in ASIA code kr", "name": "Korea, South" },
  "jm": { "order": 57261, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Jamaica", "title": "Jamaica in NORTH AMERICA code jm", "name": "Jamaica" },
  "bz": { "order": 57827, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Belize", "title": "Belize in NORTH AMERICA code bz", "name": "Belize" },
  "ly": { "order": 58361, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Libya", "title": "Libya in AFRICA code ly", "name": "Libya" },
  "lv": { "order": 58446, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Latvia", "title": "Latvia in EUROPE code lv", "name": "Latvia" },
  "fj": { "order": 60251, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Fiji", "title": "Fiji in OCEANIA code fj", "name": "Fiji" },
  "tn": { "order": 60530, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Tunisia", "title": "Tunisia in AFRICA code tn", "name": "Tunisia" },
  "fi": { "order": 61530, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Finland", "title": "Finland in EUROPE code fi", "name": "Finland" },
  "zw": { "order": 61626, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Zimbabwe", "title": "Zimbabwe in AFRICA code zw", "name": "Zimbabwe" },
  "do": { "order": 61699, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Dominican Republic", "title": "Dominican Republic in NORTH AMERICA code do", "name": "Dominican Republic" },
  "in": { "order": 62152, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "India", "title": "India in ASIA code in", "name": "India" },
  "mt": { "order": 62733, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Malta", "title": "Malta in EUROPE code mt", "name": "Malta" },
  "eg": { "order": 63096, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Egypt", "title": "Egypt in AFRICA code eg", "name": "Egypt" },
  "na": { "order": 63221, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Namibia", "title": "Namibia in AFRICA code na", "name": "Namibia" },
  "zm": { "order": 63269, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Zambia", "title": "Zambia in AFRICA code zm", "name": "Zambia" },
  "kw": { "order": 63951, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Kuwait", "title": "Kuwait in ASIA code kw", "name": "Kuwait" },
  "es": { "order": 63959, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Spain", "title": "Spain in EUROPE code es", "name": "Spain" },
  "ie": { "order": 64257, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Ireland", "title": "Ireland in EUROPE code ie", "name": "Ireland" },
  "sb": { "order": 64736, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Solomon Islands", "title": "Solomon Islands in OCEANIA code sb", "name": "Solomon Islands" },
  "ge": { "order": 65136, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Georgia", "title": "Georgia in EUROPE code ge", "name": "Georgia" },
  "ca": { "order": 65172, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Canada", "title": "Canada in NORTH AMERICA code ca", "name": "Canada" },
  "et": { "order": 65192, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Ethiopia", "title": "Ethiopia in AFRICA code et", "name": "Ethiopia" },
  "kp": { "order": 65990, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Korea, North", "title": "Korea, North in ASIA code kp", "name": "Korea, North" },
  "sm": { "order": 66726, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "San Marino", "title": "San Marino in EUROPE code sm", "name": "San Marino" },
  "au": { "order": 69068, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Australia", "title": "Australia in OCEANIA code au", "name": "Australia" },
  "td": { "order": 70250, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Chad", "title": "Chad in AFRICA code td", "name": "Chad" },
  "lu": { "order": 70877, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Luxembourg", "title": "Luxembourg in EUROPE code lu", "name": "Luxembourg" },
  "bi": { "order": 71232, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Burundi", "title": "Burundi in AFRICA code bi", "name": "Burundi" },
  "hu": { "order": 71784, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Hungary", "title": "Hungary in EUROPE code hu", "name": "Hungary" },
  "so": { "order": 72450, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Somalia", "title": "Somalia in AFRICA code so", "name": "Somalia" },
  "sz": { "order": 72472, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Swaziland", "title": "Swaziland in AFRICA code sz", "name": "Swaziland" },
  "vu": { "order": 72617, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Vanuatu", "title": "Vanuatu in OCEANIA code vu", "name": "Vanuatu" },
  "br": { "order": 72939, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Brazil", "title": "Brazil in SOUTH AMERICA code br", "name": "Brazil" },
  "my": { "order": 73469, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Malaysia", "title": "Malaysia in ASIA code my", "name": "Malaysia" },
  "gm": { "order": 73651, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Gambia", "title": "Gambia in AFRICA code gm", "name": "Gambia" },
  "sa": { "order": 73747, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Saudi Arabia", "title": "Saudi Arabia in ASIA code sa", "name": "Saudi Arabia" },
  "it": { "order": 74060, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Italy", "title": "Italy in EUROPE code it", "name": "Italy" },
  "af": { "order": 75001, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Afghanistan", "title": "Afghanistan in ASIA code af", "name": "Afghanistan" },
  "ad": { "order": 75706, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Andorra", "title": "Andorra in EUROPE code ad", "name": "Andorra" },
  "gt": { "order": 76217, "selected": true, "locked": false, "draggable": true, "resizable": true, "header": "Guatemala", "title": "Guatemala in NORTH AMERICA code gt", "name": "Guatemala" },
  "tj": { "order": 76779, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Tajikistan", "title": "Tajikistan in ASIA code tj", "name": "Tajikistan" },
  "mn": { "order": 77939, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Mongolia", "title": "Mongolia in ASIA code mn", "name": "Mongolia" },
  "cm": { "order": 78349, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Cameroon", "title": "Cameroon in AFRICA code cm", "name": "Cameroon" },
  "ng": { "order": 78551, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Nigeria", "title": "Nigeria in AFRICA code ng", "name": "Nigeria" },
  "dk": { "order": 79202, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Denmark", "title": "Denmark in EUROPE code dk", "name": "Denmark" },
  "ml": { "order": 79372, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Mali", "title": "Mali in AFRICA code ml", "name": "Mali" },
  "nl": { "order": 79575, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Netherlands", "title": "Netherlands in EUROPE code nl", "name": "Netherlands" },
  "sy": { "order": 79675, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Syria", "title": "Syria in ASIA code sy", "name": "Syria" },
  "id": { "order": 80188, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Indonesia", "title": "Indonesia in ASIA code id", "name": "Indonesia" },
  "hr": { "order": 80405, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Croatia", "title": "Croatia in EUROPE code hr", "name": "Croatia" },
  "cg": { "order": 80646, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Congo", "title": "Congo in AFRICA code cg", "name": "Congo" },
  "bg": { "order": 80834, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Bulgaria", "title": "Bulgaria in EUROPE code bg", "name": "Bulgaria" },
  "dm": { "order": 81838, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Dominica", "title": "Dominica in NORTH AMERICA code dm", "name": "Dominica" },
  "ag": { "order": 82104, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Antigua and Barbuda", "title": "Antigua and Barbuda in NORTH AMERICA code ag", "name": "Antigua and Barbuda" },
  "ba": { "order": 82989, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Bosnia and Herzegovina", "title": "Bosnia and Herzegovina in EUROPE code ba", "name": "Bosnia and Herzegovina" },
  "np": { "order": 83493, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Nepal", "title": "Nepal in ASIA code np", "name": "Nepal" },
  "cv": { "order": 83526, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Cape Verde", "title": "Cape Verde in AFRICA code cv", "name": "Cape Verde" },
  "tm": { "order": 83669, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Turkmenistan", "title": "Turkmenistan in ASIA code tm", "name": "Turkmenistan" },
  "az": { "order": 85882, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Azerbaijan", "title": "Azerbaijan in EUROPE code az", "name": "Azerbaijan" },
  "lb": { "order": 86881, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Lebanon", "title": "Lebanon in ASIA code lb", "name": "Lebanon" },
  "at": { "order": 87109, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Austria", "title": "Austria in EUROPE code at", "name": "Austria" },
  "ni": { "order": 87240, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Nicaragua", "title": "Nicaragua in NORTH AMERICA code ni", "name": "Nicaragua" },
  "va": { "order": 87339, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Vatican City", "title": "Vatican City in EUROPE code va", "name": "Vatican City" },
  "ci": { "order": 89933, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Ivory Coast", "title": "Ivory Coast in AFRICA code ci", "name": "Ivory Coast" },
  "kn": { "order": 90100, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Saint Kitts and Nevis", "title": "Saint Kitts and Nevis in NORTH AMERICA code kn", "name": "Saint Kitts and Nevis" },
  "qa": { "order": 90580, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Qatar", "title": "Qatar in ASIA code qa", "name": "Qatar" },
  "bd": { "order": 90820, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Bangladesh", "title": "Bangladesh in ASIA code bd", "name": "Bangladesh" },
  "kh": { "order": 91219, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Cambodia", "title": "Cambodia in ASIA code kh", "name": "Cambodia" },
  "cd": { "order": 92926, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Congo, Democratic Republic of", "title": "Congo, Democratic Republic of in AFRICA code cd", "name": "Congo, Democratic Republic of" },
  "bs": { "order": 93204, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Bahamas", "title": "Bahamas in NORTH AMERICA code bs", "name": "Bahamas" },
  "tr": { "order": 93584, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Turkey", "title": "Turkey in ASIA code tr", "name": "Turkey" },
  "gr": { "order": 97865, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Greece", "title": "Greece in EUROPE code gr", "name": "Greece" },
  "cy": { "order": 98605, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Cyprus", "title": "Cyprus in EUROPE code cy", "name": "Cyprus" },
  "ec": { "order": 98676, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Ecuador", "title": "Ecuador in SOUTH AMERICA code ec", "name": "Ecuador" },
  "pl": { "order": 98850, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Poland", "title": "Poland in EUROPE code pl", "name": "Poland" },
  "ne": { "order": 98990, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Niger", "title": "Niger in AFRICA code ne", "name": "Niger" },
  "tt": { "order": 99333, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Trinidad and Tobago", "title": "Trinidad and Tobago in NORTH AMERICA code tt", "name": "Trinidad and Tobago" },
  "si": { "order": 99749, "selected": false, "locked": false, "draggable": true, "resizable": true, "header": "Slovenia", "title": "Slovenia in EUROPE code si", "name": "Slovenia" }
};
